name: Deploy
on:
  repository_dispatch:
deploy:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: cloudflare/wrangler-action@1.2.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}